# Recommendation Systems-Tavsiye Sistemleri

In [2]:
import pandas as pd
import numpy as np

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
r_columns=['user_id','movie_id','rating']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',header=None,names=r_columns,usecols=range(3)) #sep=\t fonsiyonu datada tabla ayrılan yerleri kaldırır.

In [5]:
ratings

       user_id  movie_id  rating
0          196       242       3
1          186       302       3
2           22       377       1
3          244        51       2
4          166       346       1
...        ...       ...     ...
99995      880       476       3
99996      716       204       5
99997      276      1090       1
99998       13       225       2
99999       12       203       3

[100000 rows x 3 columns]

In [6]:
r_cols=['movie_id','title']
movies=pd.read_csv('ml-100k/u.item',encoding='iso-8859-1',sep='|',header=None,names=r_cols,usecols=range(2))

In [7]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [8]:
r_cols=['user_id','age','gender','profession','zipcode']
user=pd.read_table('ml-100k/u.user',sep='|',names=r_cols,usecols=range(5))

In [9]:
user

     user_id  age gender     profession zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [10]:
user.iloc[195]

user_id          196
age               49
gender             M
profession    writer
zipcode        55105
Name: 195, dtype: object

In [11]:
movies.iloc[241]

movie_id             242
title       Kolya (1996)
Name: 241, dtype: object

In [12]:
ratings=pd.merge(movies,ratings)   #movie_id ye göre eşleştirip iki tabloyu birleştirir

In [13]:
ratings

       movie_id                                      title  user_id  rating
0             1                           Toy Story (1995)      308       4
1             1                           Toy Story (1995)      287       5
2             1                           Toy Story (1995)      148       4
3             1                           Toy Story (1995)      280       4
4             1                           Toy Story (1995)       66       3
...         ...                                        ...      ...     ...
99995      1678                          Mat' i syn (1997)      863       1
99996      1679                           B. Monkey (1998)      863       3
99997      1680                       Sliding Doors (1998)      863       2
99998      1681                        You So Crazy (1994)      896       3
99999      1682  Scream of Stone (Schrei aus Stein) (1991)      916       3

[100000 rows x 4 columns]

In [14]:
ratings.sample(10)

       movie_id                         title  user_id  rating
73640       604  It Happened One Night (1934)      506       4
81649       732                   Dave (1993)      484       5
59962       434       Forbidden Planet (1956)        7       4
94250      1048          She's the One (1996)       43       3
92935      1016                Con Air (1997)      287       5
54202       369            Black Sheep (1996)      181       3
32475       211                M*A*S*H (1970)      296       4
42203       274                Sabrina (1995)      838       4
64260       483             Casablanca (1942)      305       5
52829       346           Jackie Brown (1997)      903       3

In [15]:
ratings.title.value_counts()

title
Star Wars (1977)                                583
Contact (1997)                                  509
Fargo (1996)                                    508
Return of the Jedi (1983)                       507
Liar Liar (1997)                                485
                                               ...
Tigrero: A Film That Was Never Made (1994)        1
Eye of Vichy, The (Oeil de Vichy, L') (1993)      1
Promise, The (Versprechen, Das) (1994)            1
To Cross the Rubicon (1991)                       1
Scream of Stone (Schrei aus Stein) (1991)         1
Name: count, Length: 1664, dtype: int64

In [16]:
ratings.movie_id.nunique()

1682

In [17]:
movie_ratings=ratings.pivot_table(index=['user_id'],columns=['title'],values=['rating']) # Matrix factorization

In [18]:
movie_ratings #Kullanıcılarla filmler aarsındaki ilişki tablosu

                           rating                                     \
title   'Til There Was You (1997) 1-900 (1994) 101 Dalmatians (1996)
user_id
1                             NaN          NaN                   2.0
2                             NaN          NaN                   NaN
3                             NaN          NaN                   NaN
4                             NaN          NaN                   NaN
5                             NaN          NaN                   2.0
...                           ...          ...                   ...
939                           NaN          NaN                   NaN
940                           NaN          NaN                   NaN
941                           NaN          NaN                   NaN
942                           NaN          NaN                   NaN
943                           NaN          NaN                   NaN

                                                                    \
title   12 Angry Men (1957) 187 (1997) 2 Days in the Valley (1996)
user_id
1                       5.0        NaN                         NaN
2                       NaN        NaN                         NaN
3                       NaN        2.0                         NaN
4                       NaN        NaN                         NaN
5                       NaN        NaN                         NaN
...                     ...        ...                         ...
939                     NaN        NaN                         NaN
940                     NaN        NaN                         NaN
941                     NaN        NaN                         NaN
942                     NaN        NaN                         NaN
943                     NaN        NaN                         2.0

                                                                          \
title   20,000 Leagues Under the Sea (1954) 2001: A Space Odyssey (1968)
user_id
1                                       3.0                          4.0
2                                       NaN                          NaN
3                                       NaN                          NaN
4                                       NaN                          NaN
5                                       NaN                          4.0
...                                     ...                          ...
939                                     NaN                          NaN
940                                     NaN                          NaN
941                                     NaN                          NaN
942                                     NaN                          3.0
943                                     NaN                          NaN

                                                                          ...  \
title   3 Ninjas: High Noon At Mega Mountain (1998) 39 Steps, The (1935)  ...
user_id                                                                   ...
1                                               NaN                  NaN  ...
2                                               1.0                  NaN  ...
3                                               NaN                  NaN  ...
4                                               NaN                  NaN  ...
5                                               NaN                  NaN  ...
...                                             ...                  ...  ...
939                                             NaN                  NaN  ...
940                                             NaN                  NaN  ...
941                                             NaN                  NaN  ...
942                                             NaN                  3.0  ...
943                                             NaN                  NaN  ...

                                                                         \
title   Yankee Zulu (1994) Year of the Horse (1997) You So Crazy (1994)
user_id
1                      NaN                      NaN                 NaN
2                      NaN                      NaN                 NaN
3                      NaN                      NaN                 NaN
4                      NaN                      NaN                 NaN
5                      NaN                      NaN                 NaN
...                    ...                      ...                 ...
939                    NaN                      NaN                 NaN
940                    NaN                      NaN                 NaN
941                    NaN                      NaN                 NaN
942                    NaN                      NaN                 NaN
943                    NaN                      NaN                 NaN

                                                                          \
title   Young Frankenstein (1974) Young Guns (1988) Young Guns II (1990)
user_id
1                             5.0               3.0                  NaN
2                             NaN               NaN                  NaN
3                             NaN               NaN                  NaN
4                             NaN               NaN                  NaN
5                             4.0               NaN                  NaN
...                           ...               ...                  ...
939                           NaN               NaN                  NaN
940                           NaN               NaN                  NaN
941                           NaN               NaN                  NaN
942                           NaN               NaN                  NaN
943                           NaN               4.0                  3.0

                                                                               \
title   Young Poisoner's Handbook, The (1995) Zeus and Roxanne (1997) unknown
user_id
1                                         NaN                     NaN     4.0
2                                         NaN                     NaN     NaN
3                                         NaN                     NaN     NaN
4                                         NaN                     NaN     NaN
5                                         NaN                     NaN     4.0
...                                       ...                     ...     ...
939                                       NaN                     NaN     NaN
940                                       NaN                     NaN     NaN
941                                       NaN                     NaN     NaN
942                                       NaN                     NaN     NaN
943                                       NaN                     NaN     NaN


title   Á köldum klaka (Cold Fever) (1994)
user_id
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
5                                      NaN
...                                    ...
939                                    NaN
940                                    NaN
941                                    NaN
942                                    NaN
943                                    NaN

[943 rows x 1664 columns]

In [19]:
print(list(movie_ratings.keys()))

[('rating', "'Til There Was You (1997)"), ('rating', '1-900 (1994)'), ('rating', '101 Dalmatians (1996)'), ('rating', '12 Angry Men (1957)'), ('rating', '187 (1997)'), ('rating', '2 Days in the Valley (1996)'), ('rating', '20,000 Leagues Under the Sea (1954)'), ('rating', '2001: A Space Odyssey (1968)'), ('rating', '3 Ninjas: High Noon At Mega Mountain (1998)'), ('rating', '39 Steps, The (1935)'), ('rating', '8 1/2 (1963)'), ('rating', '8 Heads in a Duffel Bag (1997)'), ('rating', '8 Seconds (1994)'), ('rating', 'A Chef in Love (1996)'), ('rating', 'Above the Rim (1994)'), ('rating', 'Absolute Power (1997)'), ('rating', 'Abyss, The (1989)'), ('rating', 'Ace Ventura: Pet Detective (1994)'), ('rating', 'Ace Ventura: When Nature Calls (1995)'), ('rating', 'Across the Sea of Time (1995)'), ('rating', 'Addams Family Values (1993)'), ('rating', 'Addicted to Love (1997)'), ('rating', 'Addiction, The (1995)'), ('rating', 'Adventures of Pinocchio, The (1996)'), ('rating', 'Adventures of Priscilla, Queen of the Desert, The (1994)'), ('rating', 'Adventures of Robin Hood, The (1938)'), ('rating', 'Affair to Remember, An (1957)'), ('rating', 'African Queen, The (1951)'), ('rating', 'Afterglow (1997)'), ('rating', 'Age of Innocence, The (1993)'), ('rating', 'Aiqing wansui (1994)'), ('rating', 'Air Bud (1997)'), ('rating', 'Air Force One (1997)'), ('rating', 'Air Up There, The (1994)'), ('rating', 'Airheads (1994)'), ('rating', 'Akira (1988)'), ('rating', 'Aladdin (1992)'), ('rating', 'Aladdin and the King of Thieves (1996)'), ('rating', 'Alaska (1996)'), ('rating', 'Albino Alligator (1996)'), ('rating', 'Alice in Wonderland (1951)'), ('rating', 'Alien (1979)'), ('rating', 'Alien 3 (1992)'), ('rating', 'Alien: Resurrection (1997)'), ('rating', 'Aliens (1986)'), ('rating', 'All About Eve (1950)'), ('rating', 'All Dogs Go to Heaven 2 (1996)'), ('rating', 'All Over Me (1997)'), ('rating', 'All Things Fair (1996)'), ('rating', 'Alphaville (1965)'), ('rating', 'Amadeus (1984)'), ('rating', 'Amateur (1994)'), ('rating', 'Amazing Panda Adventure, The (1995)'), ('rating', 'American Buffalo (1996)'), ('rating', 'American Dream (1990)'), ('rating', 'American President, The (1995)'), ('rating', 'American Strays (1996)'), ('rating', 'American Werewolf in London, An (1981)'), ('rating', 'American in Paris, An (1951)'), ('rating', 'Amistad (1997)'), ('rating', "Amityville 1992: It's About Time (1992)"), ('rating', 'Amityville 3-D (1983)'), ('rating', 'Amityville Curse, The (1990)'), ('rating', 'Amityville Horror, The (1979)'), ('rating', 'Amityville II: The Possession (1982)'), ('rating', 'Amityville: A New Generation (1993)'), ('rating', 'Amityville: Dollhouse (1996)'), ('rating', 'Amos & Andrew (1993)'), ('rating', 'An Unforgettable Summer (1994)'), ('rating', 'Anaconda (1997)'), ('rating', 'Anastasia (1997)'), ('rating', 'Andre (1994)'), ('rating', 'Angel Baby (1995)'), ('rating', 'Angel and the Badman (1947)'), ('rating', 'Angel on My Shoulder (1946)'), ('rating', 'Angela (1995)'), ('rating', 'Angels and Insects (1995)'), ('rating', 'Angels in the Outfield (1994)'), ('rating', 'Angus (1995)'), ('rating', 'Anna (1996)'), ('rating', 'Anna Karenina (1997)'), ('rating', 'Anne Frank Remembered (1995)'), ('rating', 'Annie Hall (1977)'), ('rating', 'Another Stakeout (1993)'), ('rating', "Antonia's Line (1995)"), ('rating', 'Aparajito (1956)'), ('rating', 'Apartment, The (1960)'), ('rating', 'Apocalypse Now (1979)'), ('rating', 'Apollo 13 (1995)'), ('rating', 'Apostle, The (1997)'), ('rating', 'Apple Dumpling Gang, The (1975)'), ('rating', "April Fool's Day (1986)"), ('rating', 'Apt Pupil (1998)'), ('rating', 'Aristocats, The (1970)'), ('rating', 'Army of Darkness (1993)'), ('rating', 'Around the World in 80 Days (1956)'), ('rating', 'Arrival, The (1996)'), ('rating', 'Arsenic and Old Lace (1944)'), ('rating', 'As Good As It Gets (1997)'), ('rating', 'Assassins (1995)'), ('rating', 'Assignment, The (1997)'), ('rating', 'Associate, The (1996)'), ('rating', 'Audrey Rose (1977)'), ('rating', 'August (1996)'), ('rating', 'Austin Powers: International Man of Mystery (1997)'), ('rating', 'Awfully Big Adventure, An (1995)'), ('rating', 'Ayn Rand: A Sense of Life (1997)'), ('rating', 'B*A*P*S (1997)'), ('rating', 'B. Monkey (1998)'), ('rating', 'Babe (1995)'), ('rating', 'Baby-Sitters Club, The (1995)'), ('rating', 'Babyfever (1994)'), ('rating', 'Babysitter, The (1995)'), ('rating', 'Back to the Future (1985)'), ('rating', 'Backbeat (1993)'), ('rating', 'Bad Boys (1995)'), ('rating', 'Bad Company (1995)'), ('rating', 'Bad Girls (1994)'), ('rating', 'Bad Moon (1996)'), ('rating', 'Bad Taste (1987)'), ('rating', 'Ballad of Narayama, The (Narayama Bushiko) (1958)'), ('rating', 'Balto (1995)'), ('rating', 'Bananas (1971)'), ('rating', 'Band Wagon, The (1953)'), ('rating', 'Barb Wire (1996)'), ('rating', 'Barbarella (1968)'), ('rating', 'Barcelona (1994)'), ('rating', 'Basic Instinct (1992)'), ('rating', 'Basketball Diaries, The (1995)'), ('rating', 'Basquiat (1996)'), ('rating', 'Bastard Out of Carolina (1996)'), ('rating', 'Batman & Robin (1997)'), ('rating', 'Batman (1989)'), ('rating', 'Batman Forever (1995)'), ('rating', 'Batman Returns (1992)'), ('rating', 'Baton Rouge (1988)'), ('rating', 'Bean (1997)'), ('rating', 'Beans of Egypt, Maine, The (1994)'), ('rating', 'Beat the Devil (1954)'), ('rating', 'Beautician and the Beast, The (1997)'), ('rating', 'Beautiful Girls (1996)'), ('rating', 'Beautiful Thing (1996)'), ('rating', 'Beauty and the Beast (1991)'), ('rating', 'Beavis and Butt-head Do America (1996)'), ('rating', 'Bed of Roses (1996)'), ('rating', 'Bedknobs and Broomsticks (1971)'), ('rating', 'Before Sunrise (1995)'), ('rating', 'Before and After (1996)'), ('rating', 'Before the Rain (Pred dozhdot) (1994)'), ('rating', 'Being Human (1993)'), ('rating', 'Being There (1979)'), ('rating', 'Believers, The (1987)'), ('rating', 'Belle de jour (1967)'), ('rating', 'Ben-Hur (1959)'), ('rating', 'Benny & Joon (1993)'), ('rating', 'Bent (1997)'), ('rating', 'Best Men (1997)'), ('rating', 'Best of the Best 3: No Turning Back (1995)'), ('rating', 'Better Off Dead... (1985)'), ('rating', 'Beverly Hillbillies, The (1993)'), ('rating', 'Beverly Hills Cop III (1994)'), ('rating', 'Beverly Hills Ninja (1997)'), ('rating', 'Bewegte Mann, Der (1994)'), ('rating', 'Beyond Bedlam (1993)'), ('rating', 'Beyond Rangoon (1995)'), ('rating', 'Bhaji on the Beach (1993)'), ('rating', 'Big Bang Theory, The (1994)'), ('rating', 'Big Blue, The (Grand bleu, Le) (1988)'), ('rating', 'Big Bully (1996)'), ('rating', 'Big Green, The (1995)'), ('rating', 'Big Lebowski, The (1998)'), ('rating', 'Big Night (1996)'), ('rating', 'Big One, The (1997)'), ('rating', 'Big Sleep, The (1946)'), ('rating', 'Big Squeeze, The (1996)'), ('rating', 'Billy Madison (1995)'), ('rating', 'Bio-Dome (1996)'), ('rating', 'Bird of Prey (1996)'), ('rating', 'Birdcage, The (1996)'), ('rating', 'Birds, The (1963)'), ('rating', 'Bitter Moon (1992)'), ('rating', 'Bitter Sugar (Azucar Amargo) (1996)'), ('rating', 'Black Beauty (1994)'), ('rating', 'Black Sheep (1996)'), ('rating', 'Blade Runner (1982)'), ('rating', 'Blink (1994)'), ('rating', 'Bliss (1997)'), ('rating', 'Blob, The (1958)'), ('rating', 'Blood & Wine (1997)'), ('rating', 'Blood Beach (1981)'), ('rating', "Blood For Dracula (Andy Warhol's Dracula) (1974)"), ('rating', 'Bloodsport 2 (1995)'), ('rating', 'Bloody Child, The (1996)'), ('rating', 'Blown Away (1994)'), ('rating', 'Blue Angel, The (Blaue Engel, Der) (1930)'), ('rating', 'Blue Chips (1994)'), ('rating', 'Blue Sky (1994)'), ('rating', 'Blue in the Face (1995)'), ('rating', 'Blues Brothers 2000 (1998)'), ('rating', 'Blues Brothers, The (1980)'), ('rating', 'Bob Roberts (1992)'), ('rating', 'Body Parts (1991)'), ('rating', 'Body Snatcher, The (1945)'), ('rating', 'Body Snatchers (1993)'), ('rating', 'Bogus (1996)'), ('rating', 'Bonheur, Le (1965)'), ('rating', 'Bonnie and Clyde (1967)'), ('rating', 'Boogie Nights (1997)'), ('rating', 'Boomerang (1992)'), ('rating', 'Boot, Das (1981)'), ('rating', 'Booty Call (1997)'), ('rating', 'Bottle Rocket (1996)'), ('rating', 'Bound (1996)'), ('rating', 'Boxing Helena (1993)'), ('rating', "Boy's Life 2 (1997)"), ('rating', 'Boys (1996)'), ('rating', 'Boys Life (1995)'), ('rating', 'Boys in Venice (1996)'), ('rating', 'Boys of St. Vincent, The (1993)'), ('rating', 'Boys on the Side (1995)'), ('rating', 'Boys, Les (1997)'), ('rating', 'Brady Bunch Movie, The (1995)'), ('rating', 'Braindead (1992)'), ('rating', "Bram Stoker's Dracula (1992)"), ('rating', 'Brassed Off (1996)'), ('rating', 'Braveheart (1995)'), ('rating', 'Brazil (1985)'), ('rating', 'Bread and Chocolate (Pane e cioccolata) (1973)'), ('rating', 'Breakdown (1997)'), ('rating', "Breakfast at Tiffany's (1961)"), ('rating', 'Breaking the Waves (1996)'), ('rating', 'Bride of Frankenstein (1935)'), ('rating', 'Bridge on the River Kwai, The (1957)'), ('rating', 'Bridges of Madison County, The (1995)'), ('rating', 'Bringing Up Baby (1938)'), ('rating', 'Broken Arrow (1996)'), ('rating', 'Broken English (1996)'), ('rating', 'Bronx Tale, A (1993)'), ('rating', 'Brother Minister: The Assassination of Malcolm X (1994)'), ('rating', "Brother's Kiss, A (1997)"), ('rating', 'Brothers McMullen, The (1995)'), ('rating', 'Brothers in Trouble (1995)'), ('rating', 'Browning Version, The (1994)'), ('rating', 'Buddy (1997)'), ('rating', 'Bulletproof (1996)'), ('rating', 'Bullets Over Broadway (1994)'), ('rating', 'Burnt By the Sun (1994)'), ('rating', 'Burnt Offerings (1976)'), ('rating', 'Bushwhacked (1995)'), ('rating', 'Butch Cassidy and the Sundance Kid (1969)'), ('rating', 'Butcher Boy, The (1998)'), ('rating', 'Butterfly Kiss (1995)'), ('rating', 'Bye Bye, Love (1995)'), ('rating', "C'est arrivé près de chez vous (1992)"), ('rating', 'Cabin Boy (1994)'), ('rating', 'Cable Guy, The (1996)'), ('rating', 'Calendar Girl (1993)'), ('rating', 'Canadian Bacon (1994)'), ('rating', 'Candidate, The (1972)'), ('rating', 'Candyman (1992)'), ('rating', 'Candyman: Farewell to the Flesh (1995)'), ('rating', 'Cape Fear (1962)'), ('rating', 'Cape Fear (1991)'), ('rating', 'Captives (1994)'), ('rating', 'Career Girls (1997)'), ('rating', 'Careful (1992)'), ('rating', "Carlito's Way (1993)"), ('rating', 'Carmen Miranda: Bananas Is My Business (1994)'), ('rating', 'Caro Diario (Dear Diary) (1994)'), ('rating', 'Carpool (1996)'), ('rating', 'Carrie (1976)'), ('rating', 'Carried Away (1996)'), ('rating', 'Carrington (1995)'), ('rating', 'Casablanca (1942)'), ('rating', 'Casino (1995)'), ('rating', 'Casper (1995)'), ('rating', 'Castle Freak (1995)'), ('rating', 'Cat People (1982)'), ('rating', 'Cat on a Hot Tin Roof (1958)'), ('rating', "Cats Don't Dance (1997)"), ('rating', 'Catwalk (1995)'), ('rating', 'Caught (1996)'), ('rating', 'Celestial Clockwork (1994)'), ('rating', 'Celluloid Closet, The (1995)'), ('rating', 'Celtic Pride (1996)'), ('rating', 'Cement Garden, The (1993)'), ('rating', 'Cemetery Man (Dellamorte Dellamore) (1994)'), ('rating', 'Century (1993)'), ('rating', 'Chain Reaction (1996)'), ('rating', 'Chairman of the Board (1998)'), ('rating', 'Chamber, The (1996)'), ('rating', 'Charade (1963)'), ('rating', 'Chasers (1994)'), ('rating', 'Chasing Amy (1997)'), ('rating', 'Children of the Corn: The Gathering (1996)'), ('rating', 'Children of the Revolution (1996)'), ('rating', 'Chinatown (1974)'), ('rating', 'Christmas Carol, A (1938)'), ('rating', 'Chungking Express (1994)'), ('rating', 'Ciao, Professore! (1993)'), ('rating', 'Cinderella (1950)'), ('rating', 'Cinema Paradiso (1988)'), ('rating', 'Circle of Friends (1995)'), ('rating', 'Citizen Kane (1941)'), ('rating', 'Citizen Ruth (1996)'), ('rating', 'City Hall (1996)'), ('rating', "City Slickers II: The Legend of Curly's Gold (1994)"), ('rating', 'City of Angels (1998)'), ('rating', 'City of Industry (1997)'), ('rating', 'City of Lost Children, The (1995)'), ('rating', 'Clean Slate (1994)'), ('rating', 'Clean Slate (Coup de Torchon) (1981)'), ('rating', 'Clear and Present Danger (1994)'), ('rating', 'Clerks (1994)'), ('rating', 'Client, The (1994)'), ('rating', 'Cliffhanger (1993)'), ('rating', 'Clockers (1995)'), ('rating', 'Clockwork Orange, A (1971)'), ('rating', 'Close Shave, A (1995)'), ('rating', 'Clueless (1995)'), ('rating', 'Cobb (1994)'), ('rating', 'Cold Comfort Farm (1995)'), ('rating', 'Coldblooded (1995)'), ('rating', 'Collectionneuse, La (1967)'), ('rating', 'Colonel Chabert, Le (1994)'), ('rating', 'Color of Night (1994)'), ('rating', 'Commandments (1997)'), ('rating', 'Con Air (1997)'), ('rating', 'Conan the Barbarian (1981)'), ('rating', 'Condition Red (1995)'), ('rating', 'Coneheads (1993)'), ('rating', 'Congo (1995)'), ('rating', 'Conspiracy Theory (1997)'), ('rating', 'Contact (1997)'), ('rating', 'Contempt (Mépris, Le) (1963)'), ('rating', 'Convent, The (Convento, O) (1995)'), ('rating', 'Cook the Thief His Wife & Her Lover, The (1989)'), ('rating', 'Cool Hand Luke (1967)'), ('rating', 'Cool Runnings (1993)'), ('rating', 'Cop Land (1997)'), ('rating', 'Cops and Robbersons (1994)'), ('rating', 'Copycat (1995)'), ('rating', 'Corrina, Corrina (1994)'), ('rating', 'Cosi (1996)'), ('rating', 'Country Life (1994)'), ('rating', 'Courage Under Fire (1996)'), ('rating', 'Cowboy Way, The (1994)'), ('rating', 'Craft, The (1996)'), ('rating', 'Crash (1996)'), ('rating', 'Crimson Tide (1995)'), ('rating', 'Critical Care (1997)'), ('rating', 'Cronos (1992)'), ('rating', 'Crooklyn (1994)'), ('rating', 'Crossfire (1947)'), ('rating', 'Crossing Guard, The (1995)'), ('rating', 'Crow, The (1994)'), ('rating', 'Crow: City of Angels, The (1996)'), ('rating', 'Crows and Sparrows (1949)'), ('rating', 'Crucible, The (1996)'), ('rating', 'Crude Oasis, The (1995)'), ('rating', 'Crumb (1994)'), ('rating', 'Cry, the Beloved Country (1995)'), ('rating', 'Crying Game, The (1992)'), ('rating', 'Curdled (1996)'), ('rating', 'Cure, The (1995)'), ('rating', 'Cutthroat Island (1995)'), ('rating', 'Cyclo (1995)'), ('rating', 'Cyrano de Bergerac (1990)'), ('rating', 'Cérémonie, La (1995)'), ('rating', 'D3: The Mighty Ducks (1996)'), ('rating', 'Dadetown (1995)'), ('rating', 'Daens (1992)'), ('rating', 'Damsel in Distress, A (1937)'), ('rating', 'Dances with Wolves (1990)'), ('rating', 'Dangerous Beauty (1998)'), ('rating', 'Dangerous Ground (1997)'), ('rating', 'Dangerous Minds (1995)'), ('rating', "Daniel Defoe's Robinson Crusoe (1996)"), ('rating', "Dante's Peak (1997)"), ('rating', 'Dark City (1998)'), ('rating', 'Dave (1993)'), ('rating', 'Davy Crockett, King of the Wild Frontier (1955)'), ('rating', 'Day the Earth Stood Still, The (1951)'), ('rating', 'Day the Sun Turned Cold, The (Tianguo niezi) (1994)'), ('rating', 'Daylight (1996)'), ('rating', 'Days of Thunder (1990)'), ('rating', 'Daytrippers, The (1996)'), ('rating', 'Dazed and Confused (1993)'), ('rating', 'Dead Man (1995)'), ('rating', 'Dead Man Walking (1995)'), ('rating', 'Dead Poets Society (1989)'), ('rating', 'Dead Presidents (1995)'), ('rating', 'Dear God (1996)'), ('rating', 'Death and the Maiden (1994)'), ('rating', 'Death in Brunswick (1991)'), ('rating', 'Death in the Garden (Mort en ce jardin, La) (1956)'), ('rating', 'Deceiver (1997)'), ('rating', 'Deconstructing Harry (1997)'), ('rating', 'Deep Rising (1998)'), ('rating', 'Deer Hunter, The (1978)'), ('rating', 'Delicatessen (1991)'), ('rating', 'Delta of Venus (1994)'), ('rating', 'Demolition Man (1993)'), ('rating', 'Denise Calls Up (1995)'), ('rating', 'Desert Winds (1995)'), ('rating', 'Designated Mourner, The (1997)'), ('rating', 'Desperado (1995)'), ('rating', 'Desperate Measures (1998)'), ('rating', 'Destiny Turns on the Radio (1995)'), ('rating', 'Devil in a Blue Dress (1995)'), ('rating', "Devil's Advocate, The (1997)"), ('rating', "Devil's Own, The (1997)"), ('rating', 'Diabolique (1996)'), ('rating', 'Dial M for Murder (1954)'), ('rating', 'Die Hard (1988)'), ('rating', 'Die Hard 2 (1990)'), ('rating', 'Die Hard: With a Vengeance (1995)'), ('rating', 'Die xue shuang xiong (Killer, The) (1989)'), ('rating', 'Dingo (1992)'), ('rating', 'Dirty Dancing (1987)'), ('rating', 'Disclosure (1994)'), ('rating', 'Diva (1981)'), ('rating', 'Dolores Claiborne (1994)'), ('rating', 'Don Juan DeMarco (1995)'), ('rating', "Don't Be a Menace to South Central While Drinking Your Juice in the Hood (1996)"), ('rating', 'Donnie Brasco (1997)'), ('rating', 'Doom Generation, The (1995)'), ('rating', 'Doors, The (1991)'), ('rating', 'Double Happiness (1994)'), ('rating', 'Double Team (1997)'), ('rating', 'Double vie de Véronique, La (Double Life of Veronique, The) (1991)'), ('rating', 'Down Periscope (1996)'), ('rating', 'Down by Law (1986)'), ('rating', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)'), ('rating', 'Dracula: Dead and Loving It (1995)'), ('rating', 'Dragonheart (1996)'), ('rating', 'Dream Man (1995)'), ('rating', 'Dream With the Fishes (1997)'), ('rating', 'Drop Dead Fred (1991)'), ('rating', 'Drop Zone (1994)'), ('rating', 'Drunks (1995)'), ('rating', 'Duck Soup (1933)'), ('rating', 'Dumb & Dumber (1994)'), ('rating', 'Dumbo (1941)'), ('rating', 'Dunston Checks In (1996)'), ('rating', 'Duoluo tianshi (1995)'), ('rating', 'E.T. the Extra-Terrestrial (1982)'), ('rating', 'East of Eden (1955)'), ('rating', 'Eat Drink Man Woman (1994)'), ('rating', 'Ed (1996)'), ('rating', 'Ed Wood (1994)'), ('rating', "Ed's Next Move (1996)"), ('rating', 'Eddie (1996)'), ('rating', 'Edge, The (1997)'), ('rating', 'Eighth Day, The (1996)'), ('rating', 'Emma (1996)'), ('rating', 'Empire Strikes Back, The (1980)'), ('rating', 'Enchanted April (1991)'), ('rating', 'Endless Summer 2, The (1994)'), ('rating', "Enfer, L' (1994)"), ('rating', 'English Patient, The (1996)'), ('rating', 'Englishman Who Went Up a Hill, But Came Down a Mountain, The (1995)'), ('rating', 'Entertaining Angels: The Dorothy Day Story (1996)'), ('rating', 'Eraser (1996)'), ('rating', 'Escape from L.A. (1996)'), ('rating', 'Escape from New York (1981)'), ('rating', 'Escape to Witch Mountain (1975)'), ('rating', 'Etz Hadomim Tafus (Under the Domin Tree) (1994)'), ('rating', "Eve's Bayou (1997)"), ('rating', 'Even Cowgirls Get the Blues (1993)'), ('rating', 'Evening Star, The (1996)'), ('rating', 'Event Horizon (1997)'), ('rating', 'Everest (1998)'), ('rating', 'Every Other Weekend (1990)'), ('rating', 'Everyone Says I Love You (1996)'), ('rating', 'Evil Dead II (1987)'), ('rating', 'Evita (1996)'), ('rating', 'Excess Baggage (1997)'), ('rating', 'Executive Decision (1996)'), ('rating', 'Exit to Eden (1994)'), ('rating', 'Exotica (1994)'), ('rating', 'Extreme Measures (1996)'), ('rating', 'Eye for an Eye (1996)'), ('rating', "Eye of Vichy, The (Oeil de Vichy, L') (1993)"), ('rating', 'Face/Off (1997)'), ('rating', 'Faces (1968)'), ('rating', 'Fair Game (1995)'), ('rating', 'FairyTale: A True Story (1997)'), ('rating', 'Faithful (1996)'), ('rating', 'Fall (1997)'), ('rating', 'Fallen (1998)'), ('rating', 'Falling in Love Again (1980)'), ('rating', 'Family Thing, A (1996)'), ('rating', 'Fan, The (1996)'), ('rating', 'Fantasia (1940)'), ('rating', 'Far From Home: The Adventures of Yellow Dog (1995)'), ('rating', 'Farewell My Concubine (1993)'), ('rating', 'Farewell to Arms, A (1932)'), ('rating', 'Fargo (1996)'), ('rating', 'Farinelli: il castrato (1994)'), ('rating', 'Farmer & Chase (1995)'), ('rating', 'Fast, Cheap & Out of Control (1997)'), ('rating', 'Faster Pussycat! Kill! Kill! (1965)'), ('rating', 'Fatal Instinct (1993)'), ('rating', 'Father of the Bride (1950)'), ('rating', 'Father of the Bride Part II (1995)'), ('rating', "Fathers' Day (1997)"), ('rating', 'Faust (1994)'), ('rating', 'Fausto (1993)'), ('rating', 'Favor, The (1994)'), ('rating', 'Fear (1996)'), ('rating', 'Fear of a Black Hat (1993)'), ('rating', 'Fear, The (1995)'), ('rating', 'Fearless (1993)'), ('rating', 'Feast of July (1995)'), ('rating', 'Feeling Minnesota (1996)'), ('rating', 'Female Perversions

In [20]:
movie_ratings.rating['Star Wars (1977)']

user_id
1      5.0
2      5.0
3      NaN
4      5.0
5      4.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 943, dtype: float64

In [21]:
starwars_ratings=movie_ratings.rating['Star Wars (1977)']

In [22]:
starwars_ratings

user_id
1      5.0
2      5.0
3      NaN
4      5.0
5      4.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 943, dtype: float64

In [23]:
starwars_ratings.value_counts()

Star Wars (1977)
5.0    325
4.0    176
3.0     57
2.0     16
1.0      9
Name: count, dtype: int64

In [24]:
movie_ratings.rating[['101 Dalmatians (1996)','Star Wars (1977)']].corr(numeric_only=True)

title                  101 Dalmatians (1996)  Star Wars (1977)
title
101 Dalmatians (1996)               1.000000          0.211132
Star Wars (1977)                    0.211132          1.000000

In [25]:
movie_ratings.corrwith(starwars_ratings)

        title
rating  'Til There Was You (1997)                0.872872
        1-900 (1994)                            -0.645497
        101 Dalmatians (1996)                    0.211132
        12 Angry Men (1957)                      0.184289
        187 (1997)                               0.027398
                                                   ...
        Young Guns II (1990)                     0.228615
        Young Poisoner's Handbook, The (1995)   -0.007374
        Zeus and Roxanne (1997)                  0.818182
        unknown                                  0.723123
        Á köldum klaka (Cold Fever) (1994)            NaN
Length: 1664, dtype: float64

In [26]:
similar_movies=movie_ratings.corrwith(starwars_ratings)

In [27]:
similar_movies=similar_movies.dropna()

In [28]:
similar_movies.sort_values(ascending=False)

        title
rating  Hollow Reed (1996)                        1.0
        Commandments (1997)                       1.0
        Cosi (1996)                               1.0
        No Escape (1994)                          1.0
        Stripes (1981)                            1.0
                                                 ...
        Roseanna's Grave (For Roseanna) (1997)   -1.0
        For Ever Mozart (1996)                   -1.0
        American Dream (1990)                    -1.0
        Frankie Starlight (1995)                 -1.0
        Fille seule, La (A Single Girl) (1995)   -1.0
Length: 1410, dtype: float64

In [29]:
movie_stats=ratings.groupby('title').agg({'rating':[np.size,np.mean]})

In [30]:
movie_stats.head()

                          rating
                            size      mean
title
'Til There Was You (1997)      9  2.333333
1-900 (1994)                   5  2.600000
101 Dalmatians (1996)        109  2.908257
12 Angry Men (1957)          125  4.344000
187 (1997)                    41  3.024390

In [31]:
popular_movies=movie_stats[movie_stats['rating']['size']>100]

In [32]:
popular_movies.sort_values(('rating','mean'),ascending=False)

                                 rating
                                   size      mean
title
Close Shave, A (1995)               112  4.491071
Schindler's List (1993)             298  4.466443
Wrong Trousers, The (1993)          118  4.466102
Casablanca (1942)                   243  4.456790
Shawshank Redemption, The (1994)    283  4.445230
...                                 ...       ...
Spawn (1997)                        143  2.615385
Event Horizon (1997)                127  2.574803
Crash (1996)                        128  2.546875
Jungle2Jungle (1997)                132  2.439394
Cable Guy, The (1996)               106  2.339623

[334 rows x 2 columns]

In [33]:
similar_movies_df=pd.DataFrame(similar_movies,columns=['similarity'])

In [77]:
popular_movies.columns=popular_movies.columns.get_level_values(0) #Benzer filmleri getiriyoruz
df=popular_movies.join(similar_movies_df)

In [35]:
df.head()

                                     rating    rating  similarity
       title
rating 101 Dalmatians (1996)            109  2.908257    0.211132
       12 Angry Men (1957)              125  4.344000    0.184289
       2001: A Space Odyssey (1968)     259  3.969112    0.230884
       Absolute Power (1997)            127  3.370079    0.085440
       Abyss, The (1989)                151  3.589404    0.203709

In [75]:
df.sort_values(['similarity'],ascending=False)

                                                           rating    rating  \
       title
rating Star Wars (1977)                                       583  4.358491
       Empire Strikes Back, The (1980)                        367  4.204360
       Return of the Jedi (1983)                              507  4.007890
       Raiders of the Lost Ark (1981)                         420  4.252381
       Austin Powers: International Man of Mystery (1997)     130  3.246154
...                                                           ...       ...
       Edge, The (1997)                                       113  3.539823
       As Good As It Gets (1997)                              112  4.196429
       Crash (1996)                                           128  2.546875
       G.I. Jane (1997)                                       175  3.360000
       First Wives Club, The (1996)                           160  3.018750

                                                           similarity
       title
rating Star Wars (1977)                                      1.000000
       Empire Strikes Back, The (1980)                       0.747981
       Return of the Jedi (1983)                             0.672556
       Raiders of the Lost Ark (1981)                        0.536117
       Austin Powers: International Man of Mystery (1997)    0.377433
...                                                               ...
       Edge, The (1997)                                     -0.127167
       As Good As It Gets (1997)                            -0.130466
       Crash (1996)                                         -0.148507
       G.I. Jane (1997)                                     -0.176734
       First Wives Club, The (1996)                         -0.194496

[334 rows x 3 columns]